### ISSUE TITLE
Bug: Dependency conflict with the newest Pydantic

### ISSUE THREAD

**Issue by tobias-piotr** [kinde-oss/kinde-python-sdk#29]
### Prerequisites

- [X] I have searched the repository’s issues and [Kinde community](https://thekindecommunity.slack.com/archives/C04K316BXEH) to ensure my issue isn’t a duplicate
- [X] I have checked the latest version of the library to replicate my issue
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/489e2ca9c3307c2b2e098a885e22f2239116394a/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/489e2ca9c3307c2b2e098a885e22f2239116394a/CODE_OF_CONDUCT.md)

### Describe the issue

Can't install the package when using the newest Pydantic and FastAPI:

```
The conflict is caused by:
    fastapi 0.101.0 depends on typing-extensions>=4.5.0
    kinde-python-sdk 1.2.1 depends on typing-extensions~=4.5.0
    pydantic 2.1.1 depends on typing-extensions>=4.6.1
    fastapi 0.101.0 depends on typing-extensions>=4.5.0
    kinde-python-sdk 1.2.1 depends on typing-extensions~=4.5.0
    pydantic 2.0.3 depends on typing-extensions>=4.6.1
    fastapi 0.101.0 depends on typing-extensions>=4.5.0
    kinde-python-sdk 1.2.1 depends on typing-extensions~=4.5.0
    pydantic 2.0.2 depends on typing-extensions>=4.6.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

### Library URL

https://github.com/kinde-oss/kinde-python-sdk

### Library version

1.2.1

### Operating system(s)

Ubuntu

### Operating system version(s)

22.04

**Comment by rairaman** [comment]
@tobias-piotr The current version of the SDK (1.2.2) fixes this dependency issue. Let us know if that works for you.
